---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: "03:00"
      timezone: Europe/Helsinki
    open-pull-requests-limit: 10
    commit-message:
      prefix: ci
      include: scope
    reviewers:
      - kare
    assignees:
      - kare
    labels:
      - ci
