---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      timezone: Europe/Helsinki
    open-pull-requests-limit: 10
    commit-message:
      prefix: ci
    assignees:
      - kare
    labels:
      - ci
